const projects = [
    {
        id: 'haka',
        icon: 'bi-bag-check-fill',
        title: 'Haka Company',
        descKey: 'haka_desc',
        tags: ['React', 'Node.js', 'E-commerce'],
        links: [{ type: 'live', url: 'https://www.hakacompany.com.br/' }],
    },
    {
        id: 'rickmorty',
        icon: 'bi-phone-fill',
        title: 'Rick &amp; Morty App',
        descKey: 'rick_desc',
        tags: ['Flutter', 'MVVM', 'Clean Arch'],
        links: [{ type: 'github', url: 'https://github.com/erikrestani/list_rickandmorty_app' }],
    },
    {
        id: 'wip',
        icon: 'bi-hammer',
        descKey: 'wip_desc',
        wip: true,
        tags: [],
        links: [],
    },
];

const i18n = {
    en: {
        nav_home: 'Home',
        nav_specialties: 'Specialties',
        nav_about: 'About',
        nav_projects: 'Projects',
        nav_contact: 'Contact',
        hero_title_plain: 'TURNING IDEAS INTO DIGITAL REALITY',
        hero_desc: 'Bring your ideas to life with my expertise in creativity, innovation, and adaptability. Using the most advanced technologies, I am ready to turn your dreams into tangible, impactful projects.',
        hero_btn: 'Get in touch',
        spec_title: 'MY <span>SPECIALTIES.</span>',
        spec1_title: 'MOBILE DEVELOPMENT',
        spec1_desc: 'Mobile development for low/medium/high complexity apps using Flutter',
        spec2_title: 'WEB DEVELOPMENT',
        spec2_desc: 'Web development using React, HTML/CSS/JS',
        spec3_title: 'ERP & INTEGRATIONS',
        spec3_desc: 'ERP integrations and complex business rules with Protheus and Sankhya',
        spec4_title: 'AI AGENTS',
        spec4_desc: 'AI Agents with context-aware intelligence and rule-based decision architectures',
        about_title: 'ABOUT <span>ME.</span>',
        about_desc: "I'm Érik Restani, a Full-Stack Developer passionate about building systems that actually solve problems. I specialize in mobile development with Flutter, backend solutions with Java, Node.js, and TypeScript, and ERP integrations with Protheus and Sankhya. I also develop AI Agents leveraging context-aware intelligence and rule-based decision architectures.",
        tech_title: 'TECH STACK',
        proj_title: 'MY <span>PROJECTS.</span>',
        badge_featured: 'Featured',
        badge_wip: 'Under Construction',
        haka_desc: 'Production e-commerce platform with real users and real transactions. Built for performance and scalability.',
        rick_desc: 'Flutter app with API consumption, pagination, MVVM and Clean Architecture.',
        wip_title: 'New Project',
        wip_desc: 'Something exciting is being built. Stay tuned.',
        view_live: 'Live Site',
        view_github: 'GitHub',
        coming_soon: 'Coming Soon',
        contact_title: 'GET IN <span>TOUCH.</span>',
        contact_desc: 'Have a project in mind or want to work together? Feel free to reach out!',
        footer_text: '© 2025 Érik Restani. All rights reserved.',
    },
    pt: {
        nav_home: 'Início',
        nav_specialties: 'Especialidades',
        nav_about: 'Sobre',
        nav_projects: 'Projetos',
        nav_contact: 'Contato',
        hero_title_plain: 'TRANSFORMANDO IDEIAS EM REALIDADE DIGITAL',
        hero_desc: 'Dê vida às suas ideias com minha expertise em criatividade, inovação e adaptabilidade. Com as tecnologias mais avançadas, estou pronto para transformar seus sonhos em projetos tangíveis e impactantes.',
        hero_btn: 'Entre em contato',
        spec_title: 'MINHAS <span>ESPECIALIDADES.</span>',
        spec1_title: 'DESENVOLVIMENTO MOBILE',
        spec1_desc: 'Desenvolvimento mobile para apps de baixa/média/alta complexidade com Flutter',
        spec2_title: 'DESENVOLVIMENTO WEB',
        spec2_desc: 'Desenvolvimento web utilizando React, HTML/CSS/JS',
        spec3_title: 'ERP & INTEGRAÇÕES',
        spec3_desc: 'Integrações ERP e regras de negócio complexas com Protheus e Sankhya',
        spec4_title: 'AGENTES DE IA',
        spec4_desc: 'Agentes de IA com inteligência contextual e arquiteturas de decisão baseadas em regras',
        about_title: 'SOBRE <span>MIM.</span>',
        about_desc: 'Sou Érik Restani, Desenvolvedor Full-Stack apaixonado por construir sistemas que realmente resolvem problemas. Sou especialista em desenvolvimento mobile com Flutter, soluções backend com Java, Node.js e TypeScript, e integrações ERP com Protheus e Sankhya. Também desenvolvo Agentes de IA com inteligência contextual e arquiteturas de decisão baseadas em regras.',
        tech_title: 'TECNOLOGIAS',
        proj_title: 'MEUS <span>PROJETOS.</span>',
        badge_featured: 'Destaque',
        badge_wip: 'Em Construção',
        haka_desc: 'Plataforma de e-commerce em produção com usuários e transações reais. Construída para performance e escalabilidade.',
        rick_desc: 'App Flutter com consumo de API, paginação, MVVM e Clean Architecture.',
        wip_title: 'Novo Projeto',
        wip_desc: 'Algo empolgante está sendo construído. Fique atento.',
        view_live: 'Ver Site',
        view_github: 'GitHub',
        coming_soon: 'Em Breve',
        contact_title: 'ENTRE EM <span>CONTATO.</span>',
        contact_desc: 'Tem um projeto em mente ou quer trabalhar juntos? Fique à vontade para entrar em contato!',
        footer_text: '© 2025 Érik Restani. Todos os direitos reservados.',
    },
};
